# Configuración de Spring Cloud Gateway
spring:
  cloud:
    gateway:
      # Definición de las rutas del Gateway
      routes:
        - id: stops-route
          uri: ${STOPS_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/stop/list # Coincide con las solicitudes que tienen la ruta del servicio web, en este caso solo es este
          filters:
            - AddResponseHeader=X-Powered-By, Gateway Service # Solo para agregar un encabezado
        - id: calculators-route
          uri: ${CALCULATORS_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/api/calculadora/**
          filters:
            - AddResponseHeader=X-Powered-By, Gateway Service
        - id: stephen-king-route
          uri: ${STEPHEN_KING_ROUTE_URI:https://stephen-king-api.onrender.com}
          predicates:
            - Path=/api/**
          filters:
            - AddResponseHeader=X-Powered-By, Gateway Service
        - id: postman-route
          uri: ${POSTMAN_ROUTE_URI:https://postman-echo.com}
          predicates:
            - Path=/post
          filters:
            - AddResponseHeader=X-Powered-By, Gateway Service
# Configuración de la gestión de puntos finales (endpoints)
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expone todos los puntos finales a través del protocolo HTTP
  endpoint:
    health:
      show-details: always # Muestra siempre los detalles de los puntos finales de salud
    gateway:
      enabled: true # Habilita el punto final que gestiona el Gateway
